languageCode = "en-us"
title = "rhesis"
theme = "hugo-xmin-tweak"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name   = "home"
    url    = "/"
    weight = 1
[[menu.main]]
    name   = "about & contact"
    url    = "/about/"
    weight = 2
[[menu.main]]
    name   = "posts by tags"
    url    = "/tags/"
    weight = 3
[[menu.main]]
    name   = "links"
    url    = "/links/"
    weight = 4

[params]
    footer = "[tweeter](https://twitter.com/darachm) | [github](https://github.com/darachm)"




